language: node_js

node_js: "stable"

cache:
  directories: 
  - node_modules
  - client/node_modules

before_install: cd client

script:
  - yarn install
  - yarn test
  - CI=false
  - yarn build

deploy: 
  provider: heroku
  api_key: 
    secure: $HEROKU_KEY
  app: tutortimes
  on:
    repo: ashishdommety/tutor-times
    branch: master